version: 2
updates:
  - package-ecosystem: "npm"
    directory: "attack-search"
    schedule:
      interval: "weekly"
    target-branch: "develop"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
